export const words = [
  "apple", "brave", "crane", "drake", "eagle", "flame", "grape", "house",
  "image", "joker", "knife", "lemon", "magic", "noble", "ocean", "peace",
  "quick", "reach", "scale", "tiger", "urban", "vital", "whale", "xenon",
  "youth", "zebra", "angel", "bison", "cabin", "delta", "elite", "fairy",
  "glide", "happy", "ideal", "jolly", "kites", "lunar", "mango", "ninja",
  "orbit", "piano", "quilt", "rover", "shark", "trust", "unity", "vivid",
  "worry", "xylol", "yield", "zesty", "amber", "beach", "crown", "daisy",
  "eager", "fancy", "giant", "honey",
  "mango", "nurse", "olive", "piano", "quilt", "rover", "shark", "trust",
  "unity", "vivid", "worry", "xylol", "yield", "zesty", "amber", "beach",
  "crown", "daisy", "eager", "fancy", "giant", "honey", "igloo", "jelly",
  "kitty", "lemon", "mango", "nurse", "olive", "piano", "quilt", "rover",
  "shark", "trust", "unity", "vivid", "worry", "xylol", "yield", "zesty",
  "amber", "beach", "crown", "daisy", "eager", "fancy", "giant", "honey",
  "igloo", "jelly", "kitty", "lemon", "mango", "nurse", "olive", "piano",
  "quilt", "rover", "shark", "trust", "unity", "vivid", "worry", "xylol",
  "yield", "zesty", "amber", "beach", "crown", "daisy", "eager", "fancy",
];